---
# Initialize box

# Disable firewalld on CentOS for relaxed security
- name: Disable firewalld
  service: name=firewalld state=stopped enabled=no

# Updates all packages to the latest version
- name: Update packages
  yum: name=* state=latest
