---
- hosts: all
  sudo: true
  tasks:
    - name: Disable firewalld
      service: name=firewalld state=stopped enabled=no

    # COMMENT out until ansible 1.9.4 is release/installed
    #- name: Update packages
    #  yum: name=* state=latest
    #
    #  @TODO
    #  Setup to Install PIP
    #  Setup to Install AWS CLI (after PIP is installed)
    #  Setup to Install Ansible
    #  Setup to Install CPAN (for installing Sqitch)
    #    - sudo yum install perl-devel perl-CPAN && curl -L http://cpanmin.us | perl - --sudo App::cpanminus
    #  Setup to Install postgresql (for installing Sqitch)
    #    - yum install postgresql postgresql-devel perl-DBD-Pg
    #  Setup to Install Sqitch: cpan App::Sqitch DBD::Pg

    - name: Install EPEL repository
      yum: name=epel-release state=latest

    - name: Install Remi repository
      shell: "rpm -Uvh --replacepkgs http://rpms.famillecollet.com/enterprise/remi-release-7.rpm"

    - name: Enable epel repository
      ini_file: dest=/etc/yum.repos.d/epel.repo section=epel option=enabled value=1

    - name: Enable remi repository
      ini_file: dest=/etc/yum.repos.d/remi.repo section=remi option=enabled value=1

    - name: Enable remi-php56 repository
      ini_file: dest=/etc/yum.repos.d/remi.repo section=remi-php56 option=enabled value=1

    - name: Install Required Packages
      yum: name={{ item }} state=latest
      with_items:
          - nodejs
          - npm
          - git
          - gcc
          - gcc-c++
          - make
          - flex
          - bison
          - gperf
          - ruby
          - openssl-devel
          - freetype-devel
          - fontconfig-devel
          - libicu-devel
          - sqlite-devel
          - libpng-devel
          - libjpeg-devel
          - unzip
          - php
          - php-common
          - php-xml
          - php-mbstring
          - java
          - java-1.8.0-openjdk-devel
          - rubygem-sass

    - name: NPM - Install bower
      npm: name=bower global=yes

    - name: NPM - Install grunt
      npm: name=grunt-cli global=yes

    - name: Install Gradle
      script: resources/install-gradle.sh

    - name: Download Codeception
      get_url: url=http://codeception.com/codecept.phar dest=/tmp

    - name: Set +x mode for codecept.phar
      file: path=/tmp/codecept.phar mode="u+x,g+x,o+x"

    - name: Move codecept.phar to /usr/local/bin
      command: mv /tmp/codecept.phar /usr/local/bin/codecept

    - name: Download PHPDepend
      get_url: url=http://static.pdepend.org/php/latest/pdepend.phar dest=/tmp

    - name: Set +x mode for pdepend.phar
      file: path=/tmp/pdepend.phar mode="u+x,g+x,o+x"

    - name: Move pdepend.phar to /usr/local/bin
      command: mv /tmp/pdepend.phar /usr/local/bin/pdepend

    - name: Download PHPLoc
      get_url: url=https://phar.phpunit.de/phploc.phar dest=/tmp/phploc.phar

    - name: Set +x mode for phploc.phar
      file: path=/tmp/phploc.phar mode="u+x,g+x,o+x"

    - name: Move phploc.phar to /usr/local/bin
      command: mv /tmp/phploc.phar /usr/local/bin/phploc

    - name: Download PHPMetrics
      get_url: url=https://github.com/Halleck45/PhpMetrics/raw/master/build/phpmetrics.phar dest=/tmp

    - name: Set +x mode for phpmetrics.phar
      file: path=/tmp/phpmetrics.phar mode="u+x,g+x,o+x"

    - name: Move phpmetrics.phar to /usr/local/bin
      command: mv /tmp/phpmetrics.phar /usr/local/bin/phpmetrics

    # name: Download PhantomJS-1.9.8
    #  get_url: url=https://github.com/ariya/phantomjs/archive/1.9.7.tar.gz dest=/tmp

    #- name: Untar/Gzip PhantomJS tar.gz
    #  unarchive: src=/tmp/phantomjs-1.9.7.tar.gz dest=/tmp copy=no

    #- name: Build PhantomJS (this will take a while, please be patient)
    #  command: /tmp/phantomjs-1.9.7/build.sh --confirm chdir=/tmp/phantomjs-1.9.7

    #- name: Set +x mode for phantomjs
    #  file: path=/tmp/phantomjs-1.9.7/bin/phantomjs mode="u+x,g+x,o+x"

    #- name: Move PhantomJS install to /usr/local/bin
    #  command: mv /tmp/phantomjs-1.9.7/bin/phantomjs /usr/local/bin

    #- name: Start PhantomJS Webdriver on :4444
    #  command: /usr/local/bin/phantomjs --webdriver=4444 &
    #  async: 30
    #  poll: 0
